---
# Source: harbor/templates/clair/clair-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "harbor-helm-harbor-clair"
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: clair
      port: 6060
    - name: health
      port: 6061
  selector:
    release: harbor-helm
    app: "harbor"
    component: clair
