apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true # USED FOR KUSTOMIZE
            - --sync-garbage-collection=true
            - --git-poll-interval=30s
            - --sync-interval=5m
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=master
            - --git-path=cluster-kustomize
            - --git-email=jimangel@users.noreply.github.com
            - --git-url=git@github.com:jimangel/flux-default-cluster
