---
# Source: harbor/templates/jobservice/jobservice-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-helm-harbor-jobservice"
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
type: Opaque
data:
  secret: "OUpBcXBJV1FEYmJsWUlsMQ=="
