---
# Source: nginx-ingress/templates/controller-poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.25.0
    component: "controller"
    heritage: Helm
    release: ingress-helm
  name: ingress-helm-nginx-ingress-controller
spec:
  selector:
    matchLabels:
      app: nginx-ingress
      release: ingress-helm
      component: "controller"
  minAvailable: 1
