---
# Source: harbor/templates/database/database-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "harbor-helm-harbor-database"
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
spec:
  ports:
    - port: 5432
  selector:
    release: harbor-helm
    app: "harbor"
    component: database
