---
# Source: harbor/templates/registry/registry-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: "harbor-helm-harbor-registry"
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
type: Opaque
data:
  REGISTRY_HTTP_SECRET: "T0llcUxUZHpyMm82QnJScA=="
  REGISTRY_REDIS_PASSWORD: ""
