---
# Source: harbor/templates/registry/registry-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "harbor-helm-harbor-registry"
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  selector:
    release: harbor-helm
    app: "harbor"
    component: registry
