---
# Source: dex/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.5.0
    app.kubernetes.io/instance: dex-helm
    app.kubernetes.io/version: "2.19.0"
    app.kubernetes.io/managed-by: Helm
  name: dex-helm
  namespace: nginx-ingress
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["create", "delete"]
