---
# Source: dex/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.5.0
    app.kubernetes.io/instance: dex-helm
    app.kubernetes.io/version: "2.19.0"
    app.kubernetes.io/managed-by: Helm
  name: dex-helm
stringData:
  config.yaml: |-
    issuer: http://dex.io:8080
    storage:
      config:
        inCluster: true
      type: kubernetes
    logger:
      level: debug
    web:
      http: 0.0.0.0:5556
    grpc:
      addr: 127.0.0.1:5000
      tlsCert: /etc/dex/tls/grpc/server/tls.crt
      tlsKey: /etc/dex/tls/grpc/server/tls.key
      tlsClientCA: /etc/dex/tls/grpc/ca/tls.crt
    oauth2: 
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    enablePasswordDB: true
