---
# Source: dex/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: dex
    helm.sh/chart: dex-2.5.0
    app.kubernetes.io/instance: dex-helm
    app.kubernetes.io/version: "2.19.0"
    app.kubernetes.io/managed-by: Helm
  name: dex-helm
