---
# Source: harbor/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: harbor-helm-harbor-redis
  labels:
    heritage: Helm
    release: harbor-helm
    chart: harbor
    app: "harbor"
spec:
  ports:
    - port: 6379
  selector:
    release: harbor-helm
    app: "harbor"
    component: redis
