apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  tls:
  - hosts:
    - grafana.kopish.dev
  rules:
  - host: grafana.kopish.dev 
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
